syntax on
colorscheme vendetta


set number
set numberwidth=3

" the width of a TAB is set to 4.
" Still it is a \t. It is just that
" Vim will interpret it to be having
" a width of 4
set tabstop=4
set noexpandtab

"Indents will have a width of 4
set shiftwidth=4

"Expand TABs to spaces
"set expandtab


"curle brace autocompletion
autocmd FileType c,cpp,java,sh inoremap {<CR>  {<CR><CR>}<up>
autocmd FileType c,cpp,java,sh inoremap () ()
autocmd FileType c,cpp,java,sh inoremap ( ()<left>
autocmd FileType c,cpp,java,sh set autoindent


nmap # <Home>

vmap v <Esc>

nmap J :tabp<CR> 
nmap K :tabn<CR>
nmap <C-t> :tabnew<CR>

nmap O O<Esc>

map B w

imap jk <Esc><right>
imap kj <Esc><right>

autocmd InsertEnter * set timeoutlen=700
autocmd InsertLeave * set timeoutlen=1000

" Ignore case when searching.
set ignorecase

inoremap <C-k> <C-P>
inoremap <C-j> <C-N>

nmap <up> 18k
nmap <down> 18j

function! NumberToggle()
  if(&relativenumber == 1)
      set norelativenumber
  else
	  set relativenumber
  endif
endfunc

nnoremap nt :call NumberToggle()<cr>

let mapleader = "\<Space>"
nnoremap <Leader>w :w<CR>

vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p

nnoremap <CR> G
nnoremap <BS> gg

nnoremap nl i<CR><Esc>
nnoremap E ea
