syntax on
colorscheme vendetta

" the width of a TAB is set to 4.
" Still it is a \t. It is just that
" Vim will interpret it to be having
" a width of 4
set tabstop=4

"Indents will have a width of 4
set shiftwidth=4

"Expand TABs to spaces
"set expandtab

"curle brace autocompletion
autocmd FileType c,cpp,java,sh inoremap {<CR>  {<CR><CR>}
